# Generated by Django 4.1.3 on 2022-11-21 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='joined_at',
            field=models.DateField(default=datetime.date(2022, 11, 21)),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='batch_starting',
            field=models.DateField(default=datetime.date(2022, 11, 21)),
        ),
    ]
