# Generated by Django 4.1.3 on 2022-11-21 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0004_alter_staffuser_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='joined_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='batch_starting',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
